//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGiaDung_TuanKiet.Models
{
    using System;
    using System.Collections.Generic;

    public partial class SanPham
    {
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string MaLoaiSanPham { get; set; }
        public string MaNhaSanXuat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
        public string KichThuocKhoiLuong { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public string MaMau { get; set; }
        public string MaXuatXu { get; set; }
        public string ChatLieu { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual XuatXu XuatXu { get; set; }


    }

}